---
- name: Check Python 3.13 availability
  command: which python3.13
  register: python313_check
  changed_when: false
  failed_when: false

- name: Install Python 3.13 if needed on SUSE family
  block:
    - name: Register SLES Python3 module
      shell: suseconnect -p sle-module-python3/15.7/x86_64
      ignore_errors: yes
      when: "'sles' in ansible_distribution | lower"

    - name: Install Python 3.13 on SUSE family
      zypper:
        name: python313
        state: present
  when: python313_check.rc != 0 and ansible_facts['os_family'] == 'Suse'

- name: Install Python 3.13 if needed on Debian family
  block:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Python 3.13 on Debian family
      apt:
        name: python3.13
        state: present
  when: python313_check.rc != 0 and ansible_facts['os_family'] == 'Debian'
